### ISSUE TITLE
Background pixels are not aligned with face pixels

### ISSUE THREAD

**Issue by Nadwey** [Rudxain/random-creeper-generator#1]
Uhh, Hi

As the title says the background pixels are not aligned with the face pixels, at first I was going to create a pull request, but I suck at math and my coding style is completely different than yours...

So, here is my beautiful implementation that should be [here](https://github.com/Rudxain/random-creeper-generator/blob/a356cefbc6019ae8f130e848dabe102a96614d4e/src/main.js#L42):
```js
for (let y = Math.floor(canv.height / 2 - size * 2) % size - size; y < canv.height; y += size)
    for (let x = Math.floor(canv.width / 2 - size * 2) % size - size; x < canv.width; x += size) {
```

Before:
![Face before](https://user-images.githubusercontent.com/81181783/229906941-e7c88b66-36d7-44c9-9c4b-933e63453285.png)

After:
![Face after](https://user-images.githubusercontent.com/81181783/229907033-1fdcdf59-e06f-4ac6-a0ae-3593ffc2144c.png)

I would also recommend adding Math.floor (or whatever) to the drawing functions, because it sometimes creates visual glitches:
![](https://user-images.githubusercontent.com/81181783/229908004-3738053b-bd81-45fa-9562-038047b71406.png)

**Comment by Rudxain** [comment]
> the background pixels are not aligned with the face pixels

Yep. I was hesitant to fix it, because it didn't look "bad enough". But the fact that the upper-left corner is aligned, while the other 3 corners aren't, triggers my OCD (I don't have OCD. OCD is a **much serious** condition. I just have "a little bit").

So yes, I agree that it should be fixed

> at first I was going to create a pull request, but I suck at math and my coding style is completely different than yours...

ok, it seems reasonable

> So, here is my beautiful implementation that should be [here](https://github.com/Rudxain/random-creeper-generator/blob/a356cefbc6019ae8f130e848dabe102a96614d4e/src/main.js#L42):
> 
> ```js
> for (let y = Math.floor(canv.height / 2 - size * 2) % size - size; y < canv.height; y += size)
>     for (let x = Math.floor(canv.width / 2 - size * 2) % size - size; x < canv.width; x += size) {
> ```

Seems good enough, although confusing at 1st glance. Thank you for your contribution!

> I would also recommend adding Math.floor (or whatever) to the drawing functions, because it sometimes creates visual glitches

I've been considering to completely switch to int arithmetic, lots of those problems would be fixed, and we get better performance as a bonus!

I wanted to do that after rewriting this in Rust, and switching to WASM (or Asm.js for retro-compatibility). But now I realize it would be easier to do that now, and it would make the transition/rewrite seamless.

BTW, I'm sorry for taking so long to reply. I've been very busy these weeks
